### PR TITLE
Adding ngChange support

### PR DESCRIPTION
**Pull request by tekand**
Solves #22.
Did not test it deeply and also not made changes to the .min.js version.

### CODE REVIEW

**Comment by tarasichvadim** [comment]
Shouldn't be better to add onSubmit and onCancel callbacks?

**Comment by tekand** [comment]
@tarasichvadim IMO from the app perspective it is completely irrelevant whether the user has clicked on OK or cancel, the app should only care if the value of the field changed.

**Comment by avjaz** [comment]
Any progress on this? Would love to see ng-change supported

**Comment by tekand** [comment]
Owner seems to be no responsive, you can use my repo as a dependency in the meantime.

**Comment by tekand** [comment]
@logbon72  ???

**Comment by logbon72** [comment]
This has been addressed in previous requests. See #34

**Comment by logbon72** [comment]
Apologies for not leaving a comment initially.

**Pull request closed without merging**
